In [1]:
# Import depdendencies
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Locate the file, read it into a pandas dataframe, and display the first few lines
burritos_file = "burritos.csv"
clean_burritos_df = pd.read_csv(burritos_file)
clean_burritos_df.head()

,Location,Burrito,Date,Neighborhood,Address,URL,Yelp,Google,Chips,Cost,...,Nopales,Lobster,Queso,Egg,Mushroom,Bacon,Sushi,Avocado,Corn,Zucchini
0,Donato's taco shop,California,1/18/2016,Miramar,6780 Miramar Rd,http://donatostacoshop.net/,3.5,4.2,NaN,6.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Oscar's Mexican food,California,1/24/2016,San Marcos,225 S Rancho Santa Fe Rd,http://www.yelp.com/biz/oscars-mexican-food-sa...,3.5,3.3,NaN,5.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Oscar's Mexican food,Carnitas,1/24/2016,NaN,NaN,NaN,NaN,NaN,NaN,4.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oscar's Mexican food,Carne asada,1/24/2016,NaN,NaN,NaN,NaN,NaN,NaN,5.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pollos Maria,California,1/27/2016,Carlsbad,3055 Harding St,http://pollosmaria.com/,4.0,3.8,x,6.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Replace all the variations of names
clean_burritos_df["Location"] = clean_burritos_df["Location"].replace('Kotija Jr.', 'Kotija Jr')
clean_burritos_df["Location"] = clean_burritos_df["Location"].replace("Lolita's taco shop", "Lolita's taco shop")
clean_burritos_df["Location"] = clean_burritos_df["Location"].replace('Los tacos ', 'Los Tacos ')

clean_burritos_df.to_csv("clean_burritos.csv")